Test sign up
wolox-training/adl-express-js pull request #5
Opened 2019-11-22 13:57 UTC by alanlamaswolox

## Summary
Added libraries to test and a new test for user's sign up

## Trello Card
[link](https://trello.com/c/GwuIqCnG/23-tests-de-sign-up)

2019-11-22 14:00 UTC, alanlamaswolox commented
Finally the CI succeed :tada:

2019-11-22 18:19 UTC, SantiagoFoster requested changes

2019-11-22 18:19 UTC, SantiagoFoster commented on test/controllers/user.test.js
> +  it('Creates a user', () => {
This one is fine, but you should test for border cases too. I'll let you think about what border cases I'm refering to, there are 3 of them

2019-11-26 13:22 UTC, SantiagoFoster requested changes

2019-11-26 13:22 UTC, SantiagoFoster commented on test/controllers/user.test.js
> +          .then(response => expect(JSON.parse(response.text).internal_code).toBe('email_already_in_use'))
You should not have to parse `response.text`. Check if you can access the property `internal_code` directly.  Should be in either `response.body` or `response.response.body`

2019-11-26 13:22 UTC, SantiagoFoster commented on test/controllers/user.test.js
> +        expect(response.text).toBe('Omar');
Check the signup PR. After fixing it, this should be calling the first_name property

2019-11-26 20:04 UTC, SantiagoFoster approved these changes

2019-11-27 13:07 UTC, merged